package spark.course.entity.dto;

import java.time.LocalDateTime;
import java.util.Date;

public class DiscussDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.discuss_id
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    private Integer discussId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.version
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.choose_course_id
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    private Integer chooseCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.title
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.describe
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.last_publish_time
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    private LocalDateTime lastPublishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.vote
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    private String vote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.choose_1
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    private String choose1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.choose_2
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    private String choose2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.choose_3
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    private String choose3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.choose_4
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    private String choose4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.discuss_id
     *
     * @return the value of t_discuss.discuss_id
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public Integer getDiscussId() {
        return discussId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.discuss_id
     *
     * @param discussId the value for t_discuss.discuss_id
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public void setDiscussId(Integer discussId) {
        this.discussId = discussId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.version
     *
     * @return the value of t_discuss.version
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.version
     *
     * @param version the value for t_discuss.version
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.choose_course_id
     *
     * @return the value of t_discuss.choose_course_id
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public Integer getChooseCourseId() {
        return chooseCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.choose_course_id
     *
     * @param chooseCourseId the value for t_discuss.choose_course_id
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public void setChooseCourseId(Integer chooseCourseId) {
        this.chooseCourseId = chooseCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.title
     *
     * @return the value of t_discuss.title
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.title
     *
     * @param title the value for t_discuss.title
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.describe
     *
     * @return the value of t_discuss.describe
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.describe
     *
     * @param describe the value for t_discuss.describe
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.last_publish_time
     *
     * @return the value of t_discuss.last_publish_time
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public LocalDateTime getLastPublishTime() {
        return lastPublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.last_publish_time
     *
     * @param lastPublishTime the value for t_discuss.last_publish_time
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public void setLastPublishTime(LocalDateTime lastPublishTime) {
        this.lastPublishTime = lastPublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.vote
     *
     * @return the value of t_discuss.vote
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public String getVote() {
        return vote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.vote
     *
     * @param vote the value for t_discuss.vote
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public void setVote(String vote) {
        this.vote = vote == null ? null : vote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.choose_1
     *
     * @return the value of t_discuss.choose_1
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public String getChoose1() {
        return choose1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.choose_1
     *
     * @param choose1 the value for t_discuss.choose_1
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public void setChoose1(String choose1) {
        this.choose1 = choose1 == null ? null : choose1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.choose_2
     *
     * @return the value of t_discuss.choose_2
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public String getChoose2() {
        return choose2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.choose_2
     *
     * @param choose2 the value for t_discuss.choose_2
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public void setChoose2(String choose2) {
        this.choose2 = choose2 == null ? null : choose2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.choose_3
     *
     * @return the value of t_discuss.choose_3
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public String getChoose3() {
        return choose3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.choose_3
     *
     * @param choose3 the value for t_discuss.choose_3
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public void setChoose3(String choose3) {
        this.choose3 = choose3 == null ? null : choose3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.choose_4
     *
     * @return the value of t_discuss.choose_4
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public String getChoose4() {
        return choose4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.choose_4
     *
     * @param choose4 the value for t_discuss.choose_4
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    public void setChoose4(String choose4) {
        this.choose4 = choose4 == null ? null : choose4.trim();
    }
}