server:
  port: 8080
spring:
  application:
    name: gateway
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 30
logging:
  level:
    com.netflix: debug