server:
  port: 8080
spring:
  application:
    name: gateway
management:
  security:
    enabled: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8888/eureka/
    registry-fetch-interval-seconds: 30
logging:
  level:
    com.netflix: debug