server:
  port: 8102
mybatis:
  mapperLocations: classpath:mapping/*.xml
spring:
  application:
    name: user-server
  datasource:
    name: user-server
    url: jdbc:mysql://127.0.0.1:3306/smart_online_course
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  cloud:
    loadbalancer:
      retry: false
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      editor: Spark
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8888/eureka/
logging:
  level:
    com.netflix: debug
