spring:
  application:
    name: course-ware-server
  cloud:
    loadbalancer:
      retry: false
  datasource:
    name: smart_online_course
    url: jdbc:mysql://mysql:3306/smart_online_course?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: Spark
    password: Spark
    listener:
      acknowledge-mode: manual
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 10
mybatis:
  mapperLocations: classpath:mapping/*.xml
logging:
  config: classpath:logback-spring.xml
server:
  port: 8125