server:
  port: 8101
mybatis:
  mapperLocations: classpath:mapping/*.xml

spring:
  datasource:
    name: shopping
    url: jdbc:mysql://127.0.0.1:3306/smart_online_course
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
