spring:
  application:
    name: eureka-config-center
  cloud:
    config:
      discovery:
        enabled: true
      server:
        prefix: /config
        git:
          uri: https://github.com/SparkZhou1994/SmartOnlineCourse
          search-paths: config-repo
management:
  security:
    enabled: false
encrypt:
  key: Spark
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
logging:
  level:
    com.netflix: debug