server:
  port: 8888
encrypt:
  key: Spark
spring:
  application:
    name: eureka-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SparkZhou1994/SmartOnlineCourse
          search-paths: config-repo
          username:
          password:
        prefix: /config
eureka:
  client:
    register-with-eureka: false
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
