encrypt:
  key: Spark
spring:
  application:
    name: eureka-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SparkZhou1994/SpringCloudDemo
          search-paths: config-repo
          username: 
          password: 
eureka:
  client:
    register-with-eureka: false
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000