package spark.course.entity.dto;

import java.time.LocalDateTime;
import java.util.Date;

public class HomeworkDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.homework_id
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    private Integer homeworkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.version
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.choose_course_id
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    private Integer chooseCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.describe
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.title
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.attachment
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    private String attachment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.batch
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    private Byte batch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.end_time
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.submit_time
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    private LocalDateTime submitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.range
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    private String range;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_homework.score
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    private Byte score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.homework_id
     *
     * @return the value of t_homework.homework_id
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public Integer getHomeworkId() {
        return homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.homework_id
     *
     * @param homeworkId the value for t_homework.homework_id
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public void setHomeworkId(Integer homeworkId) {
        this.homeworkId = homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.version
     *
     * @return the value of t_homework.version
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.version
     *
     * @param version the value for t_homework.version
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.choose_course_id
     *
     * @return the value of t_homework.choose_course_id
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public Integer getChooseCourseId() {
        return chooseCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.choose_course_id
     *
     * @param chooseCourseId the value for t_homework.choose_course_id
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public void setChooseCourseId(Integer chooseCourseId) {
        this.chooseCourseId = chooseCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.describe
     *
     * @return the value of t_homework.describe
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.describe
     *
     * @param describe the value for t_homework.describe
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.title
     *
     * @return the value of t_homework.title
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.title
     *
     * @param title the value for t_homework.title
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.attachment
     *
     * @return the value of t_homework.attachment
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.attachment
     *
     * @param attachment the value for t_homework.attachment
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.batch
     *
     * @return the value of t_homework.batch
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public Byte getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.batch
     *
     * @param batch the value for t_homework.batch
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public void setBatch(Byte batch) {
        this.batch = batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.end_time
     *
     * @return the value of t_homework.end_time
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.end_time
     *
     * @param endTime the value for t_homework.end_time
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.submit_time
     *
     * @return the value of t_homework.submit_time
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public LocalDateTime getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.submit_time
     *
     * @param submitTime the value for t_homework.submit_time
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public void setSubmitTime(LocalDateTime submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.range
     *
     * @return the value of t_homework.range
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public String getRange() {
        return range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.range
     *
     * @param range the value for t_homework.range
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public void setRange(String range) {
        this.range = range == null ? null : range.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_homework.score
     *
     * @return the value of t_homework.score
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public Byte getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_homework.score
     *
     * @param score the value for t_homework.score
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    public void setScore(Byte score) {
        this.score = score;
    }
}