package spark.course.entity.dto;

public class UserPasswordDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_password.user_id
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_password.version
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_password.encrypt_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    private String encryptPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_password.user_id
     *
     * @return the value of t_user_password.user_id
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_password.user_id
     *
     * @param userId the value for t_user_password.user_id
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_password.version
     *
     * @return the value of t_user_password.version
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_password.version
     *
     * @param version the value for t_user_password.version
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_password.encrypt_password
     *
     * @return the value of t_user_password.encrypt_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    public String getEncryptPassword() {
        return encryptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_password.encrypt_password
     *
     * @param encryptPassword the value for t_user_password.encrypt_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    public void setEncryptPassword(String encryptPassword) {
        this.encryptPassword = encryptPassword == null ? null : encryptPassword.trim();
    }
}