server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    ip-address: 172.19.190.83
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000