server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 172.19.190.83
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000