server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    stream:
      bindings:
        error:
          group: groupA
        insert:
          group: groupA
        update:
          group: groupA
        delete:
          group: groupA
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    hostname: localhost
zuul:
  routes:
    portal:
      url: http://localhost:8090
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
    com.netflix: debug