server:
  port: 8080
spring:
  application:
    name: gateway
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 30
zuul:
  routes:
    portal:
      url: http://localhost:8090
logging:
  level:
    com.netflix: debug