server:
  port: 8080
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 30
zuul:
  routes:
    portal:
      url: http://localhost:8090
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
    com.netflix: debug