server:
  port: 8080
spring:
  application:
    name: gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: Spark
    password: Spark
    listener:
      acknowledge-mode: manual
  sleuth:
    sampler:
      percentage: 1.0
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    hostname: localhost
zuul:
  routes:
    portal:
      url: http://localhost:8090
logging:
  config: classpath:logback-spring.xml