spring:
  application:
    name: course-server
  profiles:
    active: leader
  datasource:
    name: smart_online_course
    url: jdbc:mysql://127.0.0.1:3306/smart_online_course
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  cloud:
    loadbalancer:
      retry: false
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
mybatis:
  mapperLocations: classpath:mapping/*.xml
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
    com.netflix: debug
