package spark.course.dao;

import org.apache.ibatis.annotations.Param;
import spark.course.entity.dto.SignDTO;

import java.util.List;

public interface SignDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sign
     *
     * @mbg.generated Fri Feb 01 09:45:56 CST 2019
     */
    Integer deleteByPrimaryKey(Integer signId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sign
     *
     * @mbg.generated Fri Feb 01 09:45:56 CST 2019
     */
    Integer insert(SignDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sign
     *
     * @mbg.generated Fri Feb 01 09:45:56 CST 2019
     */
    Integer insertSelective(SignDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sign
     *
     * @mbg.generated Fri Feb 01 09:45:56 CST 2019
     */
    SignDTO selectByPrimaryKey(Integer signId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sign
     *
     * @mbg.generated Fri Feb 01 09:45:56 CST 2019
     */
    Integer updateByPrimaryKeyAndVersionSelective(SignDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sign
     *
     * @mbg.generated Fri Feb 01 09:45:56 CST 2019
     */
    Integer updateByPrimaryKeyAndVersion(SignDTO record);

    /**
    * @author Spark
    * @Description select max signId
    * @Date 10:21 AM 2/1/2019
    * @Param []
    * @return int
    **/
    Integer selectMaxSignId();

    /**
    * @author Spark
    * @Description select SingDTO list by chooseCourseId
    * @Date 10:23 AM 2/1/2019
    * @Param [chooseCourseId, start, size]
    * @return java.util.List<spark.course.entity.dto.SignDTO>
    **/
    List<SignDTO> selectByChooseCourseId(@Param("chooseCourseId") Integer chooseCourseId,
                                         @Param("start") Integer start,
                                         @Param("size") Integer size);
    
    /**
    * @author Spark
    * @Description select max batch
    * @Date 11:04 AM 2/2/2019
    * @Param [chooseCourseId]
    * @return java.lang.Integer
    **/
    Integer selectMaxBatchByChooseCourseId(Integer chooseCourseId);
}