server:
  port: 9411
spring:
  application:
    name: zipkin-server
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    hostname: localhost