server:
  port: 9411
spring:
  application:
    name: zipkin-server
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: Spark
    password: Spark
    listener:
      acknowledge-mode: manual
management:
  security:
    enabled: false