package spark.course.entity.dto;

public class CourseWareDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_ware.course_ware_id
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    private Integer courseWareId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_ware.version
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_ware.course_id
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_ware.title
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_ware.attachment
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    private String attachment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_ware.batch
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    private Byte batch;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_ware.course_ware_id
     *
     * @return the value of t_course_ware.course_ware_id
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    public Integer getCourseWareId() {
        return courseWareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_ware.course_ware_id
     *
     * @param courseWareId the value for t_course_ware.course_ware_id
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    public void setCourseWareId(Integer courseWareId) {
        this.courseWareId = courseWareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_ware.version
     *
     * @return the value of t_course_ware.version
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_ware.version
     *
     * @param version the value for t_course_ware.version
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_ware.course_id
     *
     * @return the value of t_course_ware.course_id
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_ware.course_id
     *
     * @param courseId the value for t_course_ware.course_id
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_ware.title
     *
     * @return the value of t_course_ware.title
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_ware.title
     *
     * @param title the value for t_course_ware.title
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_ware.attachment
     *
     * @return the value of t_course_ware.attachment
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_ware.attachment
     *
     * @param attachment the value for t_course_ware.attachment
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_ware.batch
     *
     * @return the value of t_course_ware.batch
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    public Byte getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_ware.batch
     *
     * @param batch the value for t_course_ware.batch
     *
     * @mbg.generated Sun Feb 03 20:08:58 CST 2019
     */
    public void setBatch(Byte batch) {
        this.batch = batch;
    }
}