package spark.course.dao;

import spark.course.entity.dto.UserDTO;

public interface UserDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Jan 24 13:00:39 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Jan 24 13:00:39 CST 2019
     */
    int insert(UserDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Jan 24 13:00:39 CST 2019
     */
    int insertSelective(UserDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Jan 24 13:00:39 CST 2019
     */
    UserDTO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Jan 24 13:00:39 CST 2019
     */
    int updateByPrimaryKeySelectiveAndVersion(UserDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Jan 24 13:00:39 CST 2019
     */
    int updateByPrimaryKeyAndVersion(UserDTO record);
}