package spark.course.dao;

import spark.course.entity.dto.UserPasswordDTO;

public interface UserPasswordDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    int insert(UserPasswordDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    int insertSelective(UserPasswordDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    UserPasswordDTO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    int updateByPrimaryKeySelective(UserPasswordDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    int updateByPrimaryKey(UserPasswordDTO record);
}