package spark.course.dao;

import spark.course.entity.dto.UserPasswordDTO;

public interface UserPasswordDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    Integer deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    Integer insert(UserPasswordDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    Integer insertSelective(UserPasswordDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    UserPasswordDTO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    Integer updateByPrimaryKeyAndVersionSelective(UserPasswordDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Thu Jan 24 13:42:16 CST 2019
     */
    Integer updateByPrimaryKeyAndVersion(UserPasswordDTO record);
}