package spark.course.dao;

import spark.course.entity.dto.UserDTO;

public interface UserDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Jan 24 13:00:39 CST 2019
     */
    Integer deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Jan 24 13:00:39 CST 2019
     */
    Integer insert(UserDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Jan 24 13:00:39 CST 2019
     */
    Integer insertSelective(UserDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Jan 24 13:00:39 CST 2019
     */
    UserDTO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Jan 24 13:00:39 CST 2019
     */
    Integer updateByPrimaryKeyAndVersionSelective(UserDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Thu Jan 24 13:00:39 CST 2019
     */
    Integer updateByPrimaryKeyAndVersion(UserDTO record);

    /**
    * @author Spark
    * @Description Select the max UserId for Primary Key
    * @Date 1:44 PM 1/28/2019
    * @Param []
    * @return int
    **/
    Integer selectMaxUserId();
}