package spark.course.dao;

import spark.course.entity.dto.UserPasswordDO;

public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Mon Jan 21 13:34:21 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Mon Jan 21 13:34:21 CST 2019
     */
    int insert(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Mon Jan 21 13:34:21 CST 2019
     */
    int insertSelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Mon Jan 21 13:34:21 CST 2019
     */
    UserPasswordDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Mon Jan 21 13:34:21 CST 2019
     */
    int updateByPrimaryKeySelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_password
     *
     * @mbg.generated Mon Jan 21 13:34:21 CST 2019
     */
    int updateByPrimaryKey(UserPasswordDO record);
}