spring:
  application:
    name: config-center
  profiles:
    active: leader
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SparkZhou1994/SmartOnlineCourse
          search-paths: config-repo
management:
  security:
    enabled: false
encrypt:
  key: Spark
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    hostname: localhost
logging:
  config: classpath:logback-spring.xml