spring:
  application:
    name: web-invoker
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: Spark
    password: Spark
    listener:
      acknowledge-mode: manual
  sleuth:
    sampler:
      percentage: 1.0
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    hostname: localhost
logging:
  config: classpath:logback-spring.xml
server:
  port: 8090
