server:
  port: 8090
spring:
  application:
    name: web-invoker
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/,http://eureka:8888/eureka/
    registry-fetch-interval-seconds: 30
logging:
  level:
    com.netflix: debug