server:
  port: 8090
spring:
  application:
    name: web-invoker
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8888/eureka/
    registry-fetch-interval-seconds: 30
feign:
  httpclient:
    enabled: false
    max-connections: 200
    max-connections-per-route: 50
  okhttp:
    enabled: false
  compression:
    request:
      enabled: true
      mime-types: application/json
      min-request-size: 2048
    response:
      enabled: true
logging:
  level:
    com.netflix: debug