spring:
  application:
    name: web-invoker
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: Spark
    password: Spark
    listener:
      acknowledge-mode: manual
  sleuth:
    sampler:
      percentage: 1.0
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    hostname: localhost
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 10
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
spark:
  security:
    browser:
      loginPage: /LoginAndRegister.html
      loginType: JSON
    code:
      image:
        length: 6
        width: 100
        url: /applepear
logging:
  config: classpath:logback-spring.xml
server:
  port: 8090
