spring:
  application:
    name: web-invoker
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: Spark
    password: Spark
    listener:
      acknowledge-mode: manual
  sleuth:
    sampler:
      percentage: 1.0
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-user-path},file:${web.upload-course-path}
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    hostname: localhost
feign:
  hystrix:
    enabled: false
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 1000
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200000
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 30000
logging:
  config: classpath:logback-spring.xml
server:
  port: 8090
web:
  upload-user-path: /smart-online-course/SmartOnlineCourse/user
  upload-course-path: /smart-online-course/SmartOnlineCourse/course
