spring:
  application:
    name: web-invoker
  profiles:
    active: leader
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 30
logging:
  level:
    com.netflix: debug