spring:
  application:
    name: web-invoker
  profiles:
    active: leader
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      acknowledge-mode: manual
  sleuth:
    sampler:
      percentage: 1.0
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    hostname: localhost
spark:
  security:
    browser:
      loginPage: /LoginAndRegister.html
      loginType: REDIRECT
    code:
      image:
        length: 6
        width: 100
        url: /applepear
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
    com.netflix: debug
