package spark.course.dao;

import org.apache.ibatis.annotations.Param;
import spark.course.entity.dto.HomeworkDTO;

import java.util.List;

public interface HomeworkDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    Integer deleteByPrimaryKey(Integer homeworkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    Integer insert(HomeworkDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    Integer insertSelective(HomeworkDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    HomeworkDTO selectByPrimaryKey(Integer homeworkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    Integer updateByPrimaryKeyAndVersionSelective(HomeworkDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_homework
     *
     * @mbg.generated Sat Feb 02 13:46:03 CST 2019
     */
    Integer updateByPrimaryKeyAndVersion(HomeworkDTO record);

    /**
    * @author Spark
    * @Description select max homeworkId 
    * @Date 2:08 PM 2/2/2019
    * @Param []
    * @return java.lang.Integer
    **/
    Integer selectMaxHomeworkId();

    /**
    * @author Spark
    * @Description select max batch by chooseCourseId
    * @Date 2:09 PM 2/2/2019
    * @Param [chooseCourseId]
    * @return java.lang.Integer
    **/
    Integer selectMaxBatchByChooseCourseId(Integer chooseCourseId);

    /**
    * @author Spark
    * @Description select HomeworkDTO list by chooseCourseId
    * @Date 2:13 PM 2/2/2019
    * @Param [chooseCourseId, start, size]
    * @return java.util.List<spark.course.entity.dto.HomeworkDTO>
    **/
    List<HomeworkDTO> selectByChooseCourseId(@Param("chooseCourseId") Integer chooseCourseId,
                                         @Param("start") Integer start,
                                         @Param("size") Integer size);
}