package spark.course.dao;

import spark.course.entity.dto.ChooseCourseDTO;

public interface ChooseCourseDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Tue Jan 29 15:40:07 CST 2019
     */
    int deleteByPrimaryKey(Integer chooseCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Tue Jan 29 15:40:07 CST 2019
     */
    int insert(ChooseCourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Tue Jan 29 15:40:07 CST 2019
     */
    int insertSelective(ChooseCourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Tue Jan 29 15:40:07 CST 2019
     */
    ChooseCourseDTO selectByPrimaryKey(Integer chooseCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Tue Jan 29 15:40:07 CST 2019
     */
    int updateByPrimaryKeyAndVersionSelective(ChooseCourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Tue Jan 29 15:40:07 CST 2019
     */
    int updateByPrimaryKeyAndVersion(ChooseCourseDTO record);

    /**
    * @author Spark
    * @Description selectChooseCourseId
    * @Date 4:03 PM 1/29/2019
    * @Param
    * @return
    **/
    ChooseCourseDTO selectChooseCourseIdByUserIdAndCourseId(ChooseCourseDTO chooseCourseDTO);
    
    /**
    * @author Spark
    * @Description get the max chooseCourseId
    * @Date 3:33 PM 1/30/2019
    * @Param []
    * @return int
    **/
    int selectMaxChooseCourseId();
}