package spark.course.dao;

import spark.course.entity.dto.ChooseCourseDTO;

import java.util.List;

public interface ChooseCourseDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Tue Jan 29 15:40:07 CST 2019
     */
    Integer deleteByPrimaryKey(Integer chooseCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Tue Jan 29 15:40:07 CST 2019
     */
    Integer insert(ChooseCourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Tue Jan 29 15:40:07 CST 2019
     */
    Integer insertSelective(ChooseCourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Tue Jan 29 15:40:07 CST 2019
     */
    ChooseCourseDTO selectByPrimaryKey(Integer chooseCourseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Tue Jan 29 15:40:07 CST 2019
     */
    Integer updateByPrimaryKeyAndVersionSelective(ChooseCourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Tue Jan 29 15:40:07 CST 2019
     */
    Integer updateByPrimaryKeyAndVersion(ChooseCourseDTO record);

    /**
    * @author Spark
    * @Description selectChooseCourseId
    * @Date 4:03 PM 1/29/2019
    * @Param
    * @return
    **/
    ChooseCourseDTO selectChooseCourseByUserIdAndCourseId(ChooseCourseDTO chooseCourseDTO);
    
    /**
    * @author Spark
    * @Description get the max chooseCourseId
    * @Date 3:33 PM 1/30/2019
    * @Param []
    * @return int
    **/
    Integer selectMaxChooseCourseId();

    /**
    * @author Spark
    * @Description get thc chooseCourseId by courseId
    * @Date 9:51 AM 1/31/2019
    * @Param [courseId]
    * @return java.util.List<spark.course.entity.dto.ChooseCourseDTO>
    **/
    List<ChooseCourseDTO> selectChooseCourseByCourseId(Integer courseId);
}