package spark.course.dao;

import spark.course.entity.dto.CourseDTO;

public interface CourseDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    int deleteByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    int insert(CourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    int insertSelective(CourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    CourseDTO selectByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    int updateByPrimaryKeySelective(CourseDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    int updateByPrimaryKey(CourseDTO record);
}