package spark.course.entity.dto;

public class CourseDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_id
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.version
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_name
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.user_id
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.catalog
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    private String catalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.avatar
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.avg_score
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    private Byte avgScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_id
     *
     * @return the value of t_course.course_id
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_id
     *
     * @param courseId the value for t_course.course_id
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.version
     *
     * @return the value of t_course.version
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.version
     *
     * @param version the value for t_course.version
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_name
     *
     * @return the value of t_course.course_name
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_name
     *
     * @param courseName the value for t_course.course_name
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.user_id
     *
     * @return the value of t_course.user_id
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.user_id
     *
     * @param userId the value for t_course.user_id
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.catalog
     *
     * @return the value of t_course.catalog
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.catalog
     *
     * @param catalog the value for t_course.catalog
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog == null ? null : catalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.avatar
     *
     * @return the value of t_course.avatar
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.avatar
     *
     * @param avatar the value for t_course.avatar
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.avg_score
     *
     * @return the value of t_course.avg_score
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public Byte getAvgScore() {
        return avgScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.avg_score
     *
     * @param avgScore the value for t_course.avg_score
     *
     * @mbg.generated Mon Jan 28 17:30:48 CST 2019
     */
    public void setAvgScore(Byte avgScore) {
        this.avgScore = avgScore;
    }
}