package spark.course.dao;

import spark.course.entity.dto.DiscussDTO;

public interface DiscussDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    int deleteByPrimaryKey(Integer discussId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    int insert(DiscussDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    int insertSelective(DiscussDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    DiscussDTO selectByPrimaryKey(Integer discussId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    int updateByPrimaryKeySelective(DiscussDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    int updateByPrimaryKey(DiscussDTO record);
}