package spark.course.dao;

import spark.course.entity.dto.DiscussDTO;

import java.util.List;

public interface DiscussDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    Integer deleteByPrimaryKey(Integer discussId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    Integer insert(DiscussDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    Integer insertSelective(DiscussDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    DiscussDTO selectByPrimaryKey(Integer discussId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    Integer updateByPrimaryKeyAndVersionSelective(DiscussDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    Integer updateByPrimaryKeyAndVersion(DiscussDTO record);

    /**
    * @author Spark
    * @Description get the max discussId
    * @Date 9:25 AM 1/31/2019
    * @Param []
    * @return int
    **/
    Integer selectMaxDiscussId();

    /**
    * @author Spark
    * @Description get discussDTO list by chooseCourseId
    * @Date 5:31 PM 1/31/2019
    * @Param [chooseCourseId]
    * @return java.util.List<spark.course.entity.dto.DiscussDTO>
    **/
    List<DiscussDTO> selectByChooseCourseId(Integer chooseCourseId);
}