package spark.course.dao;

import spark.course.entity.dto.DiscussContentDTO;

public interface DiscussContentDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss_content
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    int deleteByPrimaryKey(Integer discussContentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss_content
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    int insert(DiscussContentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss_content
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    int insertSelective(DiscussContentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss_content
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    DiscussContentDTO selectByPrimaryKey(Integer discussContentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss_content
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    int updateByPrimaryKeySelective(DiscussContentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss_content
     *
     * @mbg.generated Wed Jan 30 22:53:03 CST 2019
     */
    int updateByPrimaryKey(DiscussContentDTO record);
}